[book]
title = "我见我闻的福音"
authors = ["ioannes"]
language = "en"

[output.html]
no-section-label = true # 自动序号

[output.html.fold]
enable = false    # 是否启用截面折叠
level = 0         # 开始折叠的深度

[build]
build-dir = "docs"                # 设置输出的目录